"""Refresh Token

Revision ID: 0cbc7cc96887
Revises: fa4ae0ca9a4c
Create Date: 2024-07-30 16:52:52.681763

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0cbc7cc96887'
down_revision = 'fa4ae0ca9a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('expire_at', sa.Integer(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('crated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
